### ISSUE TITLE
Additional types not added to database

### ISSUE THREAD

**Issue by Volgi84** [tkeffer/filepile#1]
Hi, 
I installed the extension and configured it according to the instructions. Additional types are added to data records. I verified that by also installing the csv extension and my additional data types show up in the csv file. 
However, the additional data types are not added to the database. I checked with phpadmin, but the archive table does not contain the additional data types. 
I also deleted the database to test if the additional data types might only get added during creation of the database, but that did not work either.
Am I wrong in the assumption that the additional data types should also be added to the database? How would I be able to create plots of the additional data types in that case?
Thanks,
Volker

**Comment by tkeffer** [comment]
This extension merely adds the types to the data stream. It is not involved with the database --- weewx handles that.

If a type appears in the data stream, and it appears in the database schema, then it will be added to the database. So, you need to add the type to the database schema. See the section [_Adding a new type to the database_](http://www.weewx.com/docs/customizing.htm#add_archive_type) in the Customizing Guide for instructions on how to add a type.
