### ISSUE TITLE
This is Cool

### ISSUE THREAD

**Issue by VonHirsch** [tkeffer/filepile#2]
And I wish it had the option to store new columns in a new database (sqlite etc.)  thanks!

**Comment by tkeffer** [comment]
That's not really the mission of `filepile`. 

If you want to store things in a database other than the one weewxd is using, it's best to use a second instance of weewx.

**Comment by tkeffer** [comment]
Oh, and see issue #1.

**Comment by VonHirsch** [comment]
just to clarify, I wasn't suggesting using something other than native weewx.  What I mean by "new database" is adding a second sqlite database binding so that additional data columns could be stored in a new schema.  For example what is documented on [this page](https://github.com/weewx/weewx/wiki/as3935) for the as3935 weewx service.
